version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands: 
      - cd server && npm install
  build:
    commands:
      - cd server && npm run build
artifacts:
  files:
    - 'server/**/*'
  base-directory: 'build'